name: Events Demo 1
on: 
  pull_request:
    types:
    - opened
#    - edited
    - labeled
    - unlabeled
    branches:
      - main
      - 'dev-*'
      - 'feeat/**'
  workflow_dispatch: 
  push: 
  #   branches:
  #     - main
  #     - 'dev-*'
  #     - 'feat/**'
  # #   - deveploper-1
  #   paths-ignore:
  #     - '.github/workflow/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get commit message
        id: get_message
        run: echo "commit_message=${{ github.event.head_commit.message }}" >> "$GITHUB_OUTPUT"
      - name: Run specific job if commit message contains 'deploy'
        if: contains(steps.get_message.outputs.commit_message, '[deploy]')
        run: |
          echo "Commit message contains '[deploy]'. Running deployment steps..."
          
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
